name: Terraform Provisioning

on:
  push:
    branches: [dev]

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Terraform
        uses: actions/setup-terraform@v2
        with:
          terraform_version: '1.x'
      - name: Initialize Terraform
        run: terraform init
      - name: Apply Terraform configuration
        run: terraform apply -auto-approve
        outputs:
          subnet_id: ${{ steps.apply_terraform.outputs.subnet_id }}
          security_group_id: ${{ steps.apply_terraform.outputs.security_group_id }}
      - name: Use Subnet ID and Security Group ID
        run: echo "Subnet ID: ${{ steps.apply_terraform.outputs.subnet_id }}"
        echo "Security Group ID: ${{ steps.apply_terraform.outputs.security_group_id }}"